---
author: mtgingrass
comments: true
date: 2017-12-23 04:31:15+00:00
layout: post
link: http://devgin.com/dscm-depot-supply-chain-management-roles/
slug: dscm-depot-supply-chain-management-roles
title: DSCM - Depot Supply Chain Management Roles
wordpress_id: 570
categories:
- Supply Chain
tags:
- Air Force
- Depot
- dscm
- Execute
- gap
- management
- Mission
- shortfalls
- supply
- supply chain
- supportability
---

### Depot Supply Chain Management - DSCM


In this short video, I summarize some of the roles of the DSCM (pronounced "disk-um") within the Depot Supply Chain Management organizations.

In short, the DSCM team understands the future requirements for the Air Force (AF) and makes sure the trickle down supply effects are supportable as well.



 	
  1. Air Force Mission Predicted

 	
  2. Air Force Supply positions itself to meet the mission needs

 	
  3. Support for the AF Supply and Depot Repairs is altered (increase/decrease)

 	
  4. Loggies and DSCM team mitigate shortfalls or gaps in support using some of these techniques listed:

 	
    1. Expedited Deliveries

 	
    2. Expedited Purchase Requests

 	
    3. Substitute Parts

 	
    4. Engineering Waivors

 	
    5. Lateral Support

 	
    6. Other




 	
  5. Depot Repairs the parts

 	
  6. Air Force Operations Execute Missions

 	
  7. Back to step 1, repeat.


Check the video link for some more details and comment, like, subscribe. Of course, check out the Amazon ads below as well.

[embed]https://youtu.be/u3m8rCqxJb0[/embed]








