---
author: mtgingrass
comments: true
date: 2017-10-28 17:20:26+00:00
layout: post
link: http://devgin.com/supply-chain-discrepancies-rod/
slug: supply-chain-discrepancies-rod
title: Supply Chain Discrepancies ROD
wordpress_id: 320
categories:
- Supply Chain
tags:
- awaiting maintenance
- awm
- buy
- chain
- contract
- discrepancy
- exchangeable
- flow
- lead times
- lead.
- repair
- report of discrepancy
- rod
- supply
- transportation
- wip
- work in progress
---

Supply chain management activities should be designed to maximize customer value and achieve a competitive advantage. Supply chains should be efficient and timely. A full supply chain encompasses product development, sourcing (contracts), production (repairs), and logistics (transportation), as well as the software suites to handle the information exchanges.

The product (our assets) has to ultimately get to the end user, or customer. When the customer doesn't receive the parts that were planned, it could have overwhelming negative effects.

One issue with supply chains is that they are usually very complex; consisting of may pillars or functional areas separated by walls or even geographically. We call these "stove pipes" sometimes. Ownership, or command over each "stove pipe" is usually separated as well. This can cause many discrepancies within the supply chain. Ineffective supply chains will lose competitive advantage and can be very costly.

Assets, or parts, must be physically stored, transported, and accounted for. Information about the flows of the physical products must be documented in order to demand plan for the future, or forecast. This is how we determine when to place an order, what quantities to order, etc. This also can involve contracting for brand new parts, organic (in house) repairs of the parts, or a combination.

This short video clip will describe a type of error that can have huge ramifications if not addressed timely. Using a Report of Discrepancy (ROD) is one method the repair shops can use to send back an asset that is miss-identified. Learn how this effects the supply chain in this video. This is not an exhausted list by any means; however,  this should shape your thoughts about the complexities of the supply chain in order to reduce these errors in the future.



[embed]https://youtu.be/v-JlZLnAwnY[/embed]

Comment below with some of your supply chain nuances or thoughts in general.






